# Generated by Django 3.1.7 on 2021-03-18 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='User nickname')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date of creating the user')),
            ],
        ),
    ]
